# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
# 定义fastlane版本号
fastlane_version "2.27.0" 

# 定义打包平台
default_platform :ios

# 任务脚本
platform :ios do
lane :ci do|options|
branch = options[:branch]
# 自动获取当前app版本号，并补充当前编译时间为后缀
build_no = get_version_number + '.' + Time.new.strftime("%m%d%H%M")

puts "Begin to run ci"

# 递增build number
increment_build_number(build_number: build_no)

# 开始打包
gym(
# 是否清空以前的编译信息 true：是
clean:true,
# 指定打包方式，Release 或者 Debug
configuration:”Adhoc”,
# 指定打包所使用的输出方式，目前支持app-store, package, ad-hoc, enterprise, development
export_method:"ad-hoc",
# 指定输出文件夹
output_directory:"./fastlane/build",
)

# 使用fir-cli上传ipa
# 请将SDAutolayoutDemo改成你项目要打包的名称
# 请将-T后的数字更改为在fir申请的APIToken
sh "fir publish ./build/iOSTestDemo.ipa -T 59992c566b27ce19c9a63d2680c23880"

end
end


# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
